name: Python application

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Волков Виталий Андреевич"
      GROUP_NUMBER: "М3116"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Show GitHub username, Full Name and Group Number
      run: | 
        echo "GitHub Username: ${{ github.actor }}, Full Name: ${{ env.FULL_NAME }}, Group Number: ${{ env.GROUP_NUMBER }}"

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Run unit tests
      run: |
        python -m unittest discover -s /home/runner/work/geometric_lib/geometric_lib/tests

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 --ignore=F401.